### ISSUE TITLE
Hard Drive in Ultrabay Slim SATA 2nd Hdd Hard Drive Caddy Module can`t read and write

### ISSUE THREAD

**Issue by standby2010** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#1]
My Thinkpad T530, i put a Ultrabay Slim SATA 2nd Hdd Hard Drive Caddy Module in my dvdrom space.

In migftw/ThinkPad-T530-Hackintosh clover efi, the hard drive in that place can be read and write right，but in your opencore efi ,it can`t.

The Cataline system can find the hard disk in ,but it can`t read right or format it。

Hope you could find out the reason and let it work。 Thank you very much.

Well,another problem is,when i use your opencore efi,my dp port still can`t find and work，in mini-dp port or in dp port in dock either.

**Comment by 5T33Z0** [comment]
1. My optical drive is working fine. So you have to fix it on your end, since I don't use an extra HDD caddy. You probably have to add a device property for it. Compare with your Clover Config Device Properties. You have to add the appropriate file system driver as well if it's not HFSPlus, APFS or EXfat.
2. Which config are you refering to? There are 2 configs in this Folder. Read section 1 and 2 about the included configs and find out which framebuffer is necessary for your display panel's resolution (either HD or HD+) and enable the respective DSDT.aml if you use config_DSDT. If you use the DSDT-less config follow the framebuffer patching guide for your display panel if it is not HD+ https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/ivy-bridge.html#add-2

**Comment by antukst** [comment]
I also have the same problem. I use hard disk on different HDD caddy but hard disk is not supported. I have not found the solution yet.

**Comment by 5T33Z0** [comment]
I can't help you with that since I don't have a HDD Caddy in my system.

**Comment by 5T33Z0** [comment]
2 years later. Here's a patch: https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/blob/main/Additional_Files/SATA_Hotplug.plist
