### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by truongvantuan** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#12]
I created this issue to say thank you, thank you for your contribution to the hackintosh user community, you have worked so hard on this repo. I use it on Thinkpad T430 everything works very well and stable, just need create a new SSDT-PM. Could you consider integrating [YogaSMC](https://github.com/zhen-zen/YogaSMC) into this EFI? I tried it but YogaSMC only works with [Voodoops2controller](https://github.com/acidanthera/VoodooPS2) from acidanthera. When switching to Voodoops2controller from acidanthera, the trackpad does not work well. Looking forward to your response.

**Comment by 5T33Z0** [comment]
Thanks for your feedback. I've tried implementing YogaSMC but it crashes the system during boot. Unfortunately, the TrackPad works really really bad with the new Versions of VoodooPS2Controller.kext, so it's pretty much unuseable for the T430/T530 at this point. So it's not going to happen.

If you need Fan Speeds and Stats, Adding SMCProcessor and SMCSuperIO.kext that come with VirtualSMC and installing https://github.com/CloverHackyColor/HWMonitorSMC2 should allow that.

**Comment by truongvantuan** [comment]
I learned that yogaSMC depends on new VoodooPS2 to work, it won't start with VoodooPS2Controller by RehabMan. This happened to me too.

**Comment by 5T33Z0** [comment]
This is not the standard Rehabman Version! This is a modified and fixed version made compatible with OpenCore so it runs. OpenCore wouldn't even boot using the Rehabman-Version. 

Like I said: TrackPad does not work well with the Acidanthera Version. So, if you need YogaSMC, implement it yourself, since I don't need it, but I need a working Trackpad! I can hear how slow or fast the Fans are running - so I don't need a monitoring plugin to tell me that.
