### ISSUE TITLE
Big Sur 11.5.2 issues

### ISSUE THREAD

**Issue by dotexe1337** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#13]
Using Big Sur 11.5.2 on my T530 (i7 3720QM, 1920x1080 screen)

When adding in the SSDT-PM generated with the script linked in readme (also tried -target 2 to generate for MacBookPro11,1 SMBIOS), the system gets stuck here booting:
![image](https://user-images.githubusercontent.com/41847745/133695304-29f4725a-4495-40d2-8090-65761100481b.png)

When booting without SSDT-PM, the system will boot, but there is no graphics acceleration for the Intel HD 4000, and the TouchPad & Trackpoint don't work (keyboard works though).

**Comment by 5T33Z0** [comment]
Since Big Sur requires `MacBookPro11,x` to boot, `ssdtPRGen` fails to generate SSDT-PM, because it relies on Board-IDs containing data for Plugin-Type 0. As a workaround, you can either:

- use `SSDTTime` to generate a `SSDT-PLUG.aml` **or** 
- use `MacBookPro10,1` but add `-no_compat_check` to `boot-args`.

**Advantages** of using `MacBookPro10,1` with `-no_compat_check` are:

- You can boot Big Sur **and** use ssdtPRGen. 
- The CPU runs at lower clock speeds in idle since this SMBIOS was written for Ivy Bridge, while 11,x was written for Haswell CPUs. Therefore the CPU produces less heat and the machine runs quieter.
- Another benefit of using `MacBookPro10,1` is that you get the correct P-States and C-States for your CPU from ssdtPRGen.

**Disadvantages** of using `MacBookPro10,1`: 

- You won't be able to install System Updates because you won't be notified about them. But there's a simple **workaround**:

  - Change `SystemProductName` back to `MacBookPro11,1`
  - Set `csr-active-config` to `67080000` (for Big Sur)
  - Disable `-no_compat_check` boot-arg (add a '#' in front of it)
  - Reboot
  - Reset NVRAM
  - Boot macOS
  - Check for and install Updates
  - After the Updates are installed, revert to SMBIOS `MacBookPro10,1`
  - re-enable  `-no_compat_check` boot-arg 
  - Reboot

**Comment by 5T33Z0** [comment]
I've generated the SSDT-PM for you: [https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/tree/main/SSDT-PM](https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/tree/main/SSDT-PM)

SSDT-PM_i73720QM_900 is for a low frequency of 900 mHz (try this first)
SSDT-PM_i73720QM_1200 is for low frequency of 1200 mHz (use this if system crashes during boot)
