### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by juanpy0223** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#16]
Hello, thank you for sharing your great job, in my case after removing whitelist, I installed a dw1510 wifi card (bcm4322), it was ok on Mojave, but I dont see the wifi on Catalina, Big Sur or Monterrey installation of after I install... I read that you can force a kext, unader kernel section but I dont fully understand instructions.... Can please help with it?

**Comment by 5T33Z0** [comment]
" Catalina 10.15 dropped support for BCM4322 (14e4:432b). AirPortBrcm4331 plugin kext of IO80211Family kext was abandoned. This affects cards such as DW1510. Workaround is to simply install Mojave's (or High Sierra's) IO80211Family kext, i.e. copy to /L/E + repair permissions + rebuild cache (leaving /S/L/E untouched) or, if that does not work, replace Catalina's IO80211Family kext in /S/L/E by Mojave's (or High Sierra's) but this will need to be done again after each update because vanilla kexts will be re-instated."

https://osxlatitude.com/forums/topic/11138-inventory-of-supportedunsupported-wireless-cards-2-sierra-monterey/
