### ISSUE TITLE
Touchpad deadzone

### ISSUE THREAD

**Issue by argo51** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#3]
Hello! I successfully followed your guide using the DSDT-less config and everything works great, except for the touchpad.
It has some gnarly deadzones around the edges, and I have looked around for fixes and have come up dry. Is there even a fix for it, or is it just stuck like this? 

https://user-images.githubusercontent.com/81490811/112735121-936c3600-8f20-11eb-97cc-803fa88e9c8b.mp4

**Comment by 5T33Z0** [comment]
I don't know. I had to change the PS2Controller kext from Rehabmans Version (v1.9.2) to the latest one from Acidanthera because it is no longer compatible with OpenCore and cause a kernel panic.

Unfortunately, the new Kext does not work well with the Trackpad. It's probably a config thing, but I don't know where to look into.

PS2 Controller includes 4 more kexts as plugins. VooDooInput and VoodooTrackpad might be a good place to start. Click show package contents. In there is a info.plist which contains the settings.

Theres also a trackpad ssdt in the acpi folder with settings. But I don't know which ones is related to the deadzone. I gues you have to do some research on your own.

**Comment by argo51** [comment]
Alrighty, I'll look into it a bit and post back here with results if I find anything

**Comment by argo51** [comment]
I have found a working kext! I combined the various VoodooPS2 kexts from the osbaldov/T530-BigSur-EFI folder into one, disabled the Trackpad SSDT (it was causing issues with the new kext), and removed the VoodooInput kext from the config as it was no longer needed. The result is a fully working and deadzone-free trackpad with preferences and scrolling. Some gestures don't work but all the basic functionality is there, which is good enough for me personally.

Here it is:
[VoodooPS2Controller-fixed2.zip](https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/files/6217609/VoodooPS2Controller-fixed2.zip)

**Comment by 5T33Z0** [comment]
Wow, this works so much better. Especially the scrolling feels so much smoother. Thanks. I am surprised it's working at all. Since it is 1.9.2 as well. I Will compare the configs of the old build with the newest one some time. Maybe I can incorporate the settings in the latest build.
