### ISSUE TITLE
Opencore version 0.68?

### ISSUE THREAD

**Issue by gkankanh** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#4]
Awesome Work! Fantastic write up and thanks for sharing. I am trying to install Big Sur on a TP W530. I have two questions.
Which OC version are you using? Latest OC is still at 0.67. Are you using dev builds?
OC Guides advise not to reset NVRAM on Thinkpads. Did you ever run into any issues when clearing NVRAM?
Thanks

**Comment by 5T33Z0** [comment]
I am using Dortania's Nightly Builds https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

Details about the exact commit used are stored in the config.plist. Open it with a plist editor not with OpenCore configurator and you'll find it.

Use the CleanNvram.efi under "Tools" instead of the `AllowNvramReset` quirk and you won't run into problems.

**Comment by gkankanh** [comment]
Thanks for responding.
